name: Node.js Self Hosted Runner Pipeline

on:
  push:
    branches:
      - main
 
jobs:

    Dependencies:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Check Node Version
              run: node --version

            - name: Install Dependencies
              run: npm install